version: '3'

volumes:
  postgres_prod_volume:

name: local_project

services:
  note-db:
    image: postgres:14.0
    env_file:
      - .env.local
    volumes:
      - postgres_prod_volume:/var/lib/postgresql/data
    command:
      -p "6432"
    ports:
      - "${PG_PORT}:6432"