name: python-tests

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  test:
    runs-on: ubuntu-latest
    name: python tests
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
      - name: Install tests dependencies
        run: |
          python -m pip install pip==24.0
          pip install -r requirements.txt
      - name: run unit tests
        run: python -m pytest -vvs tests/
